# mongod.conf
storage:
   dbPath: /data/db

net:
   port: 27017
   bindIp: 0.0.0.0
   tls:
      mode: requireTLS
      certificateKeyFile: /etc/ssl/mongod.pem
      CAFile: /etc/ssl/ca.pem
      allowConnectionsWithoutCertificates: true

security:
   authorization: enabled
   keyFile: /etc/mongodb-keyfile


setParameter:
   searchIndexManagementHostAndPort: mongot.search-community:27028
   mongotHost: mongot.search-community:27028
   skipAuthenticationToSearchIndexManagementServer: false
   useGrpcForSearch: true
   enableLocalhostAuthBypass: true

replication:
   replSetName: rs0
